# Generated by Django 5.1.6 on 2025-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakAppMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255)),
                ('greater_less', models.CharField(max_length=10)),
                ('setpoint1', models.IntegerField(default=18)),
                ('value', models.FloatField(blank=True, null=True)),
                ('setpoint2', models.IntegerField(default=70)),
                ('timer1', models.DurationField(default='00:00:15')),
                ('timer2', models.DurationField(default='00:00:15')),
            ],
            options={
                'verbose_name': 'Leak App Master Data',
                'verbose_name_plural': 'Leak App Master Data',
                'db_table': 'leakapp_masterdata',
            },
        ),
    ]
