# Generated by Django 5.1.6 on 2025-02-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0002_leakappmasterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='greater_less',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='setpoint1',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='setpoint2',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='timer1',
            field=models.DurationField(blank=True, default='00:00:15', null=True),
        ),
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='timer2',
            field=models.DurationField(blank=True, default='00:00:15', null=True),
        ),
    ]
