# Generated by Django 4.2.6 on 2025-02-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0003_alter_leakappmasterdata_greater_less_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakAppTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField()),
                ('filter_no', models.CharField(max_length=50)),
                ('digital_input', models.CharField(max_length=20)),
                ('filter_values', models.FloatField()),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('iot_value', models.FloatField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata', verbose_name='Part Number')),
            ],
            options={
                'db_table': 'leakapp_test',
            },
        ),
        migrations.CreateModel(
            name='FOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_counter', models.IntegerField()),
                ('filterno', models.CharField(max_length=255)),
                ('filter_values', models.FloatField()),
                ('date_field', models.DateField()),
                ('iot_value', models.IntegerField()),
                ('result', models.CharField(max_length=25)),
                ('shift', models.CharField(max_length=25)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata', verbose_name='Part Number')),
            ],
            options={
                'db_table': 'foi_tbl',
            },
        ),
    ]
