# Generated by Django 5.1.6 on 2025-02-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0004_leakapptest_foi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakappmasterdata',
            name='timer1',
            field=models.DurationField(blank=True, default='00:00:05', null=True),
        ),
        migrations.CreateModel(
            name='LeakAppShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField()),
                ('filter_values', models.FloatField()),
                ('filter_no', models.CharField(max_length=50, verbose_name='Filter No')),
                ('status', models.CharField(max_length=30)),
                ('highest_value', models.FloatField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
            ],
            options={
                'db_table': 'leakapp_show_report',
            },
        ),
    ]
