# Generated by Django 5.1.6 on 2025-02-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0005_alter_leakappmasterdata_timer1_leakappshowreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
            ],
            options={
                'db_table': 'shift_tbl',
            },
        ),
        migrations.AddField(
            model_name='leakappshowreport',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift'),
            preserve_default=False,
        ),
    ]
