# Generated by Django 5.1.6 on 2025-02-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0006_shift_leakappshowreport_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakAppResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField(default=0, verbose_name='Batch Counter')),
                ('filter_no', models.CharField(max_length=50)),
                ('filter_values', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('highest_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('filter_counter_by_system', models.IntegerField()),
                ('iot_value', models.IntegerField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'db_table': 'leakapp_result_tbl',
            },
        ),
    ]
