# Generated by Django 4.2 on 2025-02-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0009_alter_leakappmasterdata_timer1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foi',
            options={'verbose_name': 'FOI', 'verbose_name_plural': 'FOI'},
        ),
        migrations.AlterModelOptions(
            name='leakappmasterdata',
            options={'verbose_name': 'Parts', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='leakappresult',
            options={'verbose_name': 'Leak Result', 'verbose_name_plural': 'Leak Results'},
        ),
        migrations.AlterModelOptions(
            name='leakappshowreport',
            options={'verbose_name': 'Leak Report', 'verbose_name_plural': 'Leak Report'},
        ),
        migrations.AlterModelOptions(
            name='leakapptest',
            options={'verbose_name': 'Leak Test', 'verbose_name_plural': 'Leak Tests'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
