# Generated by Django 4.2 on 2025-02-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0010_alter_foi_options_alter_leakappmasterdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leakapptest',
            old_name='date_field',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='leakapptest',
            old_name='iot_value',
            new_name='highest_value',
        ),
        migrations.RemoveField(
            model_name='leakapptest',
            name='digital_input',
        ),
        migrations.AddField(
            model_name='leakapptest',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leakapptest',
            name='status',
            field=models.CharField(default='OK', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leakapptest',
            name='filter_no',
            field=models.CharField(max_length=50, verbose_name='Filter No'),
        ),
        migrations.AlterField(
            model_name='leakapptest',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata'),
        ),
    ]
