# Generated by Django 4.2 on 2025-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0012_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakappresult',
            name='highest_value',
        ),
        migrations.AlterField(
            model_name='leakappresult',
            name='iot_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
