# Generated by Django 4.2 on 2025-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0013_remove_leakappresult_highest_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myplclog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodstatus', models.IntegerField()),
                ('part_number', models.CharField(max_length=25)),
                ('server_connection_1', models.IntegerField(blank=True, null=True)),
                ('server_connection_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
