# Generated by Django 4.2 on 2025-03-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0014_myplclog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myplclog',
            table='myplclog',
        ),
    ]
