# Generated by Django 4.2 on 2025-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0016_remove_leakappresult_filter_counter_by_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foi',
            old_name='filter_counter',
            new_name='batch_counter',
        ),
        migrations.RenameField(
            model_name='foi',
            old_name='date_field',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='foi',
            old_name='filterno',
            new_name='filter_no',
        ),
        migrations.RemoveField(
            model_name='foi',
            name='iot_value',
        ),
        migrations.RemoveField(
            model_name='foi',
            name='result',
        ),
        migrations.AlterField(
            model_name='foi',
            name='shift',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
