# Generated by Django 4.2 on 2025-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0017_rename_filter_counter_foi_batch_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YCalvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_no', models.CharField(max_length=25)),
                ('c_value', models.FloatField()),
                ('m_value', models.FloatField()),
            ],
            options={
                'db_table': 'y_cal_values',
            },
        ),
    ]
