# Generated by Django 4.2 on 2025-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0018_ycalvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ycalvalues',
            name='filter_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
