# Generated by Django 4.2 on 2025-03-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0019_alter_ycalvalues_filter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplclog',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata'),
        ),
    ]
