# Generated by Django 4.2 on 2025-03-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0020_alter_myplclog_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOIHighest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField(blank=True, null=True)),
                ('filter_values', models.FloatField()),
                ('filter_no', models.CharField(max_length=50, verbose_name='Filter No')),
                ('status', models.CharField(default='Not Ok', max_length=30)),
                ('highest_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'db_table': 'foihighest',
            },
        ),
    ]
