# Generated by Django 4.2 on 2025-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0021_foihighest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakappresult',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foihighest',
            name='status',
            field=models.CharField(default='NOK', max_length=30),
        ),
    ]
